In [3]:
import numpy as np

## Numpy Array

In [2]:
myList = [20,30,40]

In [4]:
type(myList)

list

In [7]:
np.array(myList)

array([20, 30, 40])

In [8]:
matrixList = [[10,20,30],[20,30,40],[30,40,50]]

In [9]:
np.array(matrixList)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## Arange

In [10]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## Zeros

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Linspace

In [20]:
np.linspace(0,10,20) ## aradaki rakamlar eşit

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## Eye

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random

In [25]:
np.random.randn(4) #Numpy dizisi döndürüyor

array([-0.40343119,  0.00910172, -0.24163644,  1.62338387])

In [26]:
np.random.rand(4,4)

array([[0.86871751, 0.19316294, 0.99186602, 0.23534647],
       [0.1256528 , 0.53854824, 0.04471067, 0.30209539],
       [0.85766501, 0.52011764, 0.61130237, 0.38711647],
       [0.46916059, 0.72823253, 0.04052462, 0.4073675 ]])

In [27]:
np.random.randint(1,10) #It returns integer, last number is not involved

8

In [31]:
np.random.randint(1,300,3)

array([219, 231,  87])

In [4]:
myNumpySer = np.arange(30)

In [5]:
print(myNumpySer)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [9]:
myRandSer = np.random.randint(0,200,30)

In [10]:
print(myRandSer)

[ 65  35   0 105  59  25 182  18  58  74  14 171  34 196  53  98 179  72
 120 110  64 150 178 107 135  62  23  79 162  20]


## Numpy Series Methods

In [7]:
myNumpySer.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [41]:
myNumpySer.max()

29

In [42]:
myRandSer.max()

192

In [43]:
myRandSer.min()

0

In [12]:
myRandSer.argmax()

13

In [45]:
myRandSer.argmin()

4

In [47]:
myNumpySer.shape ## Reshape doesn't change what's inside. 

(30,)

In [49]:
reshapeSer = myNumpySer.reshape(5,6)