In [1]:
import numpy as np

In [2]:
mySer = np.arange(0,15)

In [3]:
mySer[5]

5

In [4]:
mySer[3:5]

array([3, 4])

In [5]:
mySer[3:8] = -5 ## Adds -5 between third and 8th index

In [6]:
mySer

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [9]:
otSer = np.arange(0,24)

In [10]:
otSer

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [11]:
slicingSer = otSer[4:9]

In [12]:
slicingSer

array([4, 5, 6, 7, 8])

In [14]:
slicingSer[:] = 700

In [15]:
slicingSer

array([700, 700, 700, 700, 700])

In [16]:
otSer

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [22]:
## Without changing original
serEg = np.arange(0,24)

In [23]:
serEgCop = serEg.copy()

In [24]:
serEgSlicing = serEgCop[3:6]

In [25]:
serEgSlicing[:] = 800

In [27]:
print(serEgSlicing)
print(serEgCop)
print(serEg)

[800 800 800]
[  0   1   2 800 800 800   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


## Matrix

In [29]:
myList = [[10,20,30],[20,30,40],[40,50,60]]

In [30]:
myMatrixSer = np.array(myList)

In [31]:
print(myMatrixSer)

[[10 20 30]
 [20 30 40]
 [40 50 60]]


In [33]:
myMatrixSer[0][2]

30

In [34]:
myMatrixSer[0,2]

30

In [36]:
myMatrixSer[0:,2]

array([30, 40, 60])

In [38]:
newList = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [39]:
newMatrix = np.array(newList)

In [40]:
print(newMatrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [41]:
newMatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## Operations

In [44]:
newSer = np.random.randint(1,1000,25)

In [45]:
newSer

array([440, 163, 380, 819, 451, 632, 826, 481, 274, 205, 169, 943, 176,
       717,  49, 583, 404, 215, 511, 127, 121, 729, 124, 351, 274])

In [46]:
newSer > 500

array([False, False, False,  True, False,  True,  True, False, False,
       False, False,  True, False,  True, False,  True, False, False,
        True, False, False,  True, False, False, False])

In [47]:
resSer = newSer > 500

In [54]:
newSer[resSer]

array([819, 632, 826, 943, 717, 583, 511, 729])

In [55]:
finalSer = np.arange(0,24)

In [57]:
finalSer * finalSer

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [58]:
np.sqrt(finalSer)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])